# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out`
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: 'XS8X7CCCSP',
      issuer_id: 'c886e52f-37a0-4ef8-a051-2024e3d7c2e6',
      key_filepath: "./fastlane/AuthKey_XS8X7CCCSP.p8", # Path to your .p8 file
      in_house: false # true for enterprise accounts, false for standard accounts
    )

    match(type: "appstore", include_mac_in_profiles: true, readonly: true)

    increment_build_number(xcodeproj: "AI360.xcodeproj")

    build_app(
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates",
      clean: true,
      export_options: {
        output_directory: "./build/iOS/output",
        installerSigningCertificate: ENV["sigh_com.korlab.ai360_appstore_certificate-name"],
        provisioningProfiles: {
          "com.korlab.ai360": ENV["sigh_com.korlab.ai360_appstore_profile-name"]
        },
        signingStyle: "manual",
        teamId: ENV["sigh_com.korlab.ai360_appstore_team-id"]
      },
      workspace: "AI360.xcworkspace",
      scheme: "AI360"
    )

    # Upload to TestFlight
    upload_to_testflight(
      api_key: api_key,
      uses_non_exempt_encryption: true
    )
  end
end
